-- 1. Retrieve all columns from the customer table.

Select * from customer;

-- 2. Display only film_id, title, and rating from the film table.

Select film_id, title,rating 
from film;

--3. Retrieve the first 15 records from the actor table.

Select actor_id, first_name, last_name
from actor
limit 15;

--4. Retrieve all customers and sort them by last_name in ascending order.

Select *
FROM customer
Order BY last_name asc;

--5. Display payment_id, customer_id, and amount, sorted by amount from lowest to highest.

Select  payment_id,
        customer_id,
		amount
from payment
Order By amount asc;

--6. Retrieve customers sorted by:
    - first_name in ascending order
    - last_name in descending order

Select * 
from customer
Order By first_name asc, last_name desc;

--7. Retrieve all payments where the amount is greater than 5.

Select *
from payment
Where amount > 5;


--8. Retrieve all payments where the amount is between 3.99 and 6.99.

Select *
from payment
Where amount BETWEEN 3.99 and 6.99;

--9. Retrieve all customers whose first_name starts with the letter J.

Select * 
from customer
Where first_name like 'J%';

--10. Retrieve all films where the description contains the word “Action”.

Select * 
from film
Where description like '%Action%';

--11. Retrieve payments greater than 7, sorted by amount in descending order.

Select * 
from payment
Where amount > 7
Order By amount desc;

--12 Retrieve customers whose first name ends with “n”, sorted alphabetically.

Select *
from customer
Where first_name like '%n'
Order By first_name asc;

-- 13. Calculate the total amount spent by each customer.

Select customer_id, sum(amount) as total_amount
from payment
Group By customer_id
Order By total_amount desc;

-- 14. Retrieve the average payment amount per customer.

Select customer_id, round(avg(amount),2) as avg_amt
from payment
Group By customer_id
Order By avg_amt desc;

-- 15. Calculate the total revenue generated by each staff member.

Select staff_id, sum(amount) as total_revenue
from payment
Group By staff_id
Order By total_revenue desc;

-- 16. Identify the top 5 customers based on total payment amount.

Select customer_id, sum(amount) as total
from payment
Group By customer_id
Order By total desc
Limit 5;

--17. Find the average film length per release year.

Select film_id,avg(length),release_year
from film
Group By release_year,film_id;

--18. Retrieve the highest single payment amount in the payment table.

Select payment_id, sum(amount) as total_amount
from payment
Group By payment_id
Order By total_amount desc
Limit 1;

--19. Count how many payments each customer has made.

Select customer_id, payment_id, count(amount) as num_count
from payment
Group By customer_id,payment_id;

--20. Retrieve customers who are active and sort them by first_name.

Select customer_id, sum(active)
from customer
Group By customer_id
Order By first_name asc;
